kind: Service
apiVersion: v1
metadata:
  name: tg-gateway-svc
  labels:
    app: tg-gateway
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: tg-gateway
  type: ClusterIP
